apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: f1signalforge

type: Opaque
data:
  POSTGRES_PASSWORD: ZjFzZi1wYXNzd29yZA== # f1sf-password
  DATABASE_URL: cG9zdGdyZXM6Ly9mMXNmLXVzZXI6ZjFzZi1wYXNzd29yZEBmMXNpZ25hbGZvcmdlLXBnOjU0MzIvZjFzaWduYWxmb3JnZS1kYj9zc2xtb2RlPWRpc2FibGU=
  #postgres://f1sf-user:f1sf-password@f1signalforge-pg:5432/f1signalforge-db?sslmode=disable