apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: f1signalforge-pg
  namespace: f1signalforge
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: f1signalforge
spec:
  serviceName: f1signalforge-pg
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: f1signalforge

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: f1signalforge

    spec:
      # Security context ensures the container runs as a non-root user with a specific group ID.
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999

      containers:
        - name: postgres
          image: postgres:18-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              value: f1signalforge-db

            - name: POSTGRES_USER
              value: f1sf-user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U f1sf-user -d f1signalforge-db
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U f1sf-user -d f1signalforge-db
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app.kubernetes.io/name: postgres
          app.kubernetes.io/part-of: f1signalforge

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi